version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: piscineds_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Replace with your actual student login
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - piscine_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: piscineds_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - piscine_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  piscine_network:
    driver: bridge